// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "be969d4f-4c2e-4fa6-ac2e-f35e18a3bfea");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1705786304);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1705786313);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1705786296);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1705786273);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0af87fcc-2168-487a-b29f-ff9634ec4b1d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1705786306");
user_pref("browser.startup.homepage_override.buildID", "20210903235534");
user_pref("browser.startup.homepage_override.mstone", "92.0");
user_pref("browser.startup.lastColdStartupCheck", 1705786276);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1705786290627");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "92.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "d96b2eb2ae4e4336bfd76c254e0127be");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210903235534");
user_pref("extensions.lastAppVersion", "92.0");
user_pref("extensions.lastPlatformVersion", "92.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"8fe19d3f-0d2f-41e7-90bc-277afabbaabd\",\"formautofill@mozilla.org\":\"7bdc9bf3-bd46-46a8-b120-1c4f71370d20\",\"pictureinpicture@mozilla.org\":\"76ca8e72-6b23-4183-a0cb-1a8d447508ed\",\"screenshots@mozilla.org\":\"4bf84380-46a0-4450-bc30-75c700be04bc\",\"webcompat-reporter@mozilla.org\":\"1d47f64a-3d07-4687-aff5-6de5d64bb2c9\",\"webcompat@mozilla.org\":\"7f8fcf4d-5795-404c-ad9d-e30baf0a1f4c\",\"default-theme@mozilla.org\":\"2d864ca5-b563-4dce-a8bd-e7432dc38d13\",\"google@search.mozilla.org\":\"e2026081-f2a3-40e6-b67d-0fddf708fcf4\",\"amazondotcom@search.mozilla.org\":\"786c34d3-2979-4378-89d5-61fe0f963d4b\",\"wikipedia@search.mozilla.org\":\"efcafba6-6db3-421f-a99d-d61a6dc1569d\",\"bing@search.mozilla.org\":\"a955c0e9-afda-4041-9b6c-4be55297e8d8\",\"ddg@search.mozilla.org\":\"bf58ef60-2582-4cbd-8b17-195527c20a1d\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1705786310);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "724627f0-4708-404d-8a02-000b9b55c479");
user_pref("toolkit.startup.last_success", 1705786271);
user_pref("toolkit.telemetry.cachedClientID", "435d5363-97d6-450e-ae9f-099b021aa541");
user_pref("toolkit.telemetry.previousBuildID", "20210903235534");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
